import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    marginTop: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  text: {
    fontSize: 20,
    alignSelf: "center",
    marginTop: 30,
    marginBottom: 10,
    color: "chocolate",
    fontWeight: "bold",
  },
  form: {
    height: "80%",
    width: "90%",
    backgroundColor: "white",
    borderRadius: 15,
  },
  logo: {
    resizeMode: "contain",
    flex: 1,
    height: 50,
    width: 250,
    alignSelf: "center",
    marginTop: 30,
    marginBottom: 10,
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
    borderWidth: 2,
    fontSize: 17,
    borderColor: "black",
    borderWeight: 1,
  },
  button: {
    backgroundColor: "chocolate",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 20,
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
  },
  footerText: {
    fontSize: 16,
    color: "gray",
  },
  footerLink: {
    color: "black",
    fontSize: 16,
  },
  background: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
  },
});
