import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    marginTop: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  form: {
    height: "45%",
    width: "90%",
    backgroundColor: "white",
    borderRadius: 15,
  },
  containerinput: {
    flex: 2,
    height: "80%",
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
    borderWidth: 2,
    fontSize: 17,
  },
  button: {
    backgroundColor: "#212427",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 15,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 20,
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 80,
  },
  footerText: {
    fontSize: 16,
    color: "gray",
    marginTop: 35,
    alignSelf: "center",
    marginBottom: 30,
  },
  footerLink: {
    color: "black",
    fontSize: 16,
  },
  containerlogo: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "black",
    borderTopEndRadius: "15px",
    borderTopLeftRadius: "15px",
    marginBottom: 10,
    height: "20%",
  },
  logo: {
    resizeMode: "contain",
    flex: 1,
    height: 40,
    width: 150,
    alignSelf: "center",
    marginTop: 15,
    marginBottom: 15,
  },
  background: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "center",
  },
});
