const municipalityOptions = [
    { label: 'Angat', value: 'Angat' },
    { label: 'Balagtas', value: 'Balagtas' },
    { label: 'Baliuag', value: 'Baliuag' },
    { label: 'Bocaue', value: 'Bocaue' },
    { label: 'Bulacan', value: 'Bulacan' },
    { label: 'Bustos', value: 'Bustos' },
    { label: 'Calumpit', value: 'Calumpit' },
    { label: 'Doña Remedios Trinidad', value: 'Doña Remedios Trinidad' },
    { label: 'Guiguinto', value: 'Guiguinto' },
    { label: 'Hagonoy', value: 'Hagonoy' },
    { label: 'Malolos', value: 'Malolos' },
    { label: 'Marilao', value: 'Marilao' },
    { label: 'Meycauayan', value: 'Meycauayan' },
    { label: 'Norzagaray', value: 'Norzagaray' },
    { label: 'Obando', value: 'Obando' },
    { label: 'Pandi', value: 'Pandi' },
    { label: 'Paombong', value: 'Paombong' },
    { label: 'Plaridel', value: 'Plaridel' },
    { label: 'Pulilan', value: 'Pulilan' },
    { label: 'San Ildefonso', value: 'San Ildefonso' },
    { label: 'San Jose Del Monte', value: 'San Jose Del Monte' },
    { label: 'San Miguel', value: 'San Miguel' },
    { label: 'San Rafael', value: 'San Rafael' },
    { label: 'Sta. Maria', value: 'Sta. Maria' },
    { label: 'Valenzuela', value: 'Valenzuela' },
  ];
export default municipalityOptions;